### ISSUE TITLE
Atom feed

### ISSUE THREAD

**Issue by JohnVeness** [dpt/davespace.co.uk#1]
Hi. My feed reader no longer seems to like your http://www.davespace.co.uk/blog-all.atom feed. It says "at line 1, column 0, no element found". Hope this is an easy fix for you!

The last article it fetched OK was the "Cogs!" one from June, so the problem started after that. (It might be a problem with my feed reader TBH!)

**Comment by dpt** [comment]
Hi John. Hmm, I don't see a problem here. I've got Thunderbird and The Old Reader both fetching it successfully. To be fair, it's failing to validate cleanly <https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.davespace.co.uk%2Fblog-all.atom#l2>

The fact that your reader is complaining about line 1, colum 0 makes me think that it's failed to download the feed correctly. Could it be that?

**Comment by JohnVeness** [comment]
Yeah, I'm not really sure what's going on. I've also had other readers (on the same device) read it OK. I'll report it to the reader maintainer.

**Comment by JohnVeness** [comment]
PS I saw you deleted your twitter - I hope all is OK?

**Comment by dpt** [comment]
Yeah, I found myself obsessively checking Twitter, Discord, SoundCloud, ... so deleted them all.

**Comment by JohnVeness** [comment]
For the record, this did turn out to be a bug in the reader app I was using, now fixed :relaxed:
